name: React CI

# This workflow runs on pushes and pull requests to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Defines the Node.js versions to test against
    strategy:
      matrix:
        node-version: [20.x] # Use a version that matches your development environment

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Sets up the specified version of Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Caches npm dependencies to speed up future runs

    # Step 3: Installs your project's dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Runs your unit tests
    - name: Run unit tests
      run: npm test # This command executes the test script defined in your package.json

